CREATE OR REPLACE FUNCTION editapp() RETURNS TRIGGER AS $editapp$
DECLARE
BEGIN
  UPDATE APPSETTINGS SET ENAME = NEW.ename WHERE ENAME = OLD.ename;
  RETURN NULL;
END;

$editapp$ LANGUAGE plpgsql;

CREATE TRIGGER editapp AFTER UPDATE ON EVENTS FOR EACH ROW
EXECUTE PROCEDURE editapp();