var eventsdb = require ('../db/events');
var usersdb = require('../db/users');
var appsdb = require('../db/apps');
var lecturesdb = require('../db/lectures');

exports.settings = function(req, res) {
	if (req.params.id) {
		if (req.session.role == "admin") {
			eventsdb.geteventbyname(req.params.id, function(evento) {
				if (evento == null)
					console.log("error getting user");
				else {
					res.method = 'GET';
					res.render('newapp', {title : 'App settings' , eventname: evento[0].fullname, appid: req.params.id, user: req.session.user });
					}
				});
		} else if (req.session.role == "user") {
			eventsdb.geteventname(req.session.user, req.params.id, function(evento) {
				if (evento == null) {
					console.log("error getting user");
					res.redirect('back');
				} else {
					res.method = 'GET';
					res.render('newapp', {title : 'App settings' , eventname: evento[0].fullname, appid: req.params.id, user: req.session.user });
				}
			});
		}
	} else {
		res.redirect('back');
	}
}

exports.build = function(req, res) {
	if (req.params.id) {
		var sys = require('sys');
		var exec = require('child_process').exec;
		var child;
		var fs = require('fs');
		var htmlfile = '<script type="text/javascript">\n\t$(".clickme").click( function () {\n\t\tvar $hidden = $("#hidden" + this.id.substr(7));\n\t\t$hidden.css({ "display": "block" });\n\t});\n\n\t$(".hidden").click( function () {\n\t\tvar $hidden = $("#hidden" + this.id.substr(6));\n\t\t$hidden.css({ "display": "none" });\n\t});\n</script>';
		fs.open("./gen/" + req.params.id  +"/assets/events.html", "w+", function (err) {
			if (err) {
				res.send(500);
				console.log(err);
			} else {
  				console.log('File opened correctly');
  			}
		});
		//events html file generated by the events
		lecturesdb.getall(req.params.id, function (lectures) {
			if (lectures == null) {
				res.send(500);
			} else {
				console.log(lectures);
				console.log(lectures.length);
				for (var i = 0; i < lectures.length; i++) {
					var time1, time2; //TODO: convert dates
					htmlfile += '<div class="event">\n\t<div id="clickme'+ i + '" class="clickme">\n\t\t<img src="./img/calendar.png" />' + lectures[i].lecttitle + 
					'</div>\n\t<div id="hidden' + i + '" class="hidden">\n\t\t<sub class="subscript"><img src="./img/user.png" /> ' + lectures[i].lectturer + ' <br/><img src="./img/time.png" />' time1 + ':' + time2 + '</sub>\n\t</div>\n</div>';
				}
			}
		});
		htmlfile +="<br/><br/><br/><br/><br/><br/><br/>";
		//guess current folder
		fs.writeFile("./gen/" + req.params.id  +"/assets/events.html", htmlfile, function (err) {
			if (err) {
				res.send(500);
				console.log(err);
			} else {
  				console.log('It\'s saved!');
  			}
		});
		// executes the script used for generating the actual mobile app
		child = exec("sh ./script.sh " + req.params.id, function (error, stdout, stderr) {
  			sys.print('Output: ' + stdout);
  			if (error !== null) {
	    		console.log('exec error: ' + error);
  			}
		});
		console.log("App has been generated, check errors"); //if something bad happens at least by now
		res.redirect('/event/' + req.params.id);
	} else {
		res.redirect('back');
	}
}
/*
 * POST
 */

 exports.save = function(req, res) {
 	if (req.params.id) {
		appsdb.update(req.params.id, req.body.descr, req.body.logo, req.body.twit, req.body.fb, req.body.ever, req.body.ios, req.body.andr, req.params.id, function(appl) {
			if (appl == null) {
				console.log("error saving application settings");
				res.redirect('back');
			} else {
				res.redirect('back');
			}
		});
	} else {
		res.redirect('back');
	}
 }
